apiVersion: v1
kind: Service
metadata:
  name: juice-shop
spec:
  type: NodePort
  selector: { app: juice-shop }
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008          # participant 0X uses 30001..30008
